### ISSUE TITLE
OPDS server

### ISSUE THREAD

**Issue by yannickulrich** [pborzenkov/koreader-syncd#28]
Thanks for the great work, @pborzenkov! I've started experimenting with [extending](https://gitlab.com/yannickulrich/koreader-syncd/-/tree/opds?ref_type=heads) this a bit to include a [OPDS endpoint you can use to move books to KOReader](https://github.com/koreader/koreader/wiki/OPDS-support).

There's no real reasons to have this as part of this project (except that I don't want to run two servers) so I'd understand if you don't want to merge this. If you do, let me know and I'll open a PR

**Comment by pborzenkov** [comment]
I'm on the edge about this.

While I do appreciate the effort, I think this adds too much complexity to the otherwise simple project. I personally use Calibre's OPDS server and am quite happy with it.

**Comment by yannickulrich** [comment]
Yeah, fair enough, this is why I was asking. I'm happy enough maintaining my fork, at least for personal use. Should I close this then?
